### ISSUE TITLE
Image opened in new browser tab in Chrome when image is dragged into editor area

### ISSUE THREAD

**Issue by dinbrasil** [RonnyWeiss/APEX-Unleash-RichTextEditor#12]
When we drag a local file to the editor window, the browser opens another tab and show the image. 
When we come back to the editor page, the image is not always loaded (sometimes it is loaded, It seems related to the image size, but I could not check for sure)

Chrome version  87.0.4280.141 

When we use Firefox it works fine. 

When using Safari it does not work at all. 

Regards,

**Comment by RonnyWeiss** [comment]
Hello Thank you for the issue. I have fixed the issue in Version 2.1.1 Hope you'll have fun with the plugin
