### ISSUE TITLE
Having two Rich Text Fields on a single page

### ISSUE THREAD

**Issue by mikedavidson1959blue** [RonnyWeiss/APEX-Unleash-RichTextEditor#13]
Hi Ronny,

On my Apex page I have two Rich Text Fields, each of which I'd like to be able to drop images into. The first Rich Text field works perfectly, however the second one does not seem to be responsive to image dropping - is this a known constraint of the plug-in? Is there a work around? 

As always really appreciate hearing back.

Yours,

Mike Davidson - www.cConix.com

**Comment by RonnyWeiss** [comment]
Which version are you using? V5 oder V4 and what is your APEX Version. I think this should work but you need to add the plug-in multiple times on the page. One for the first item and one for the seconds. How you handle this?

**Comment by RonnyWeiss** [comment]
Can you please check new version 2.1.2.1? because in APEX 20.2 and CKE V5 only one instance could be used and I have add the option to have multiple CKE V5 items on one page

**Comment by mikedavidson1959blue** [comment]
Hi Ronny, thank you very much for the reply. I currently have version 2.1.2 installed, CKEditor is V5 and I am using Apex 20.2. I'll download and install the latest version and let you know how I get on. Your plug-in is superb and I'll definitely be buying you a couple of coffees! Mike

**Comment by RonnyWeiss** [comment]
Thank you very much! Hope the Update will work. 😀

**Comment by RonnyWeiss** [comment]
And sorry for late reply but this repository Was not subscribed from me so I missed the Issue 😀

**Comment by RonnyWeiss** [comment]
Please keep in my to make one dynamic Action per rte item 😉

**Comment by RonnyWeiss** [comment]
Does it work?

**Comment by mikedavidson1959blue** [comment]
Hi Ronny,

Really sorry for the delay in responding, I've been travelling a lot and have also really busy at work!

I installed the latest version of the RTE plug-in and it works perfectly, so thank you very very much.

Glad to hear that the coffee money transfer worked!

Thanks again.

Mike




[horizontal bar]
Mike Davidson
cConix, CEO
[cConix]
4036294009
1644 Broadview Road
Calgary, Alberta T2N3H1
http://www.cConix.com<http://www.cconix.com/>


________________________________

**Comment by RonnyWeiss** [comment]
Hello Mike

No problem! 

Yes has arrived, thanks again for that. 

And yes that's how it should be, glad it works! 

Kind regards

Ronny
