### ISSUE TITLE
Mit der aktivieren Apex Option "Friendly URL" werden keine Bilder im RTE angezeigt.

### ISSUE THREAD

**Issue by madmexx2002** [RonnyWeiss/APEX-Unleash-RichTextEditor#14]
Hallo Ronny

Wie immer erstmal ein dickes Danke. Danke! 

Bei aktivierter Option "Friendly URL" werden keine Bilder im RTE angezeigt. Die Bildgröße wird richtig angezeigt und der HTML- Quelltext zeigt keine unterschiede zur Ausführung ohne "Friendly URL". Auch das mit dem Plugin gespeicherte CLOB kann hinterher mit CLOB Load 2 ohne Probleme mit Bildern wie gewünscht angezeigt werden. 

Gruß Mark

**Comment by RonnyWeiss** [comment]
Hallo Vielen Dank für das Kompliment!

Also da der URL Mechanismus im CLOB Load 2 und im Unleash RTE gleich sind kann es eigentlich nicht sein, dass es im CL2 funktioniert und im URTE nicht! 

Habe es auch grade mal unter ronnyweiss.app probiert und es funktioniert auch dort sauber mit Friendly URLs, sowohl im CKE4 als auch im CK5! Können Sie bitte nochmal den PL/SQL Code checken? Bzw. mir mal den Code zusenden?

Welche APEX Version und welche Plug-in Version nutzen sie?

LG Ronny

**Comment by RonnyWeiss** [comment]
Ich nutze für die URLs ja eine APEX API daher auch nocham ldie Frage nach der genauen APEX Version. Kann ja auch sein, dass es ein BUG im APEX JS ist.

**Comment by madmexx2002** [comment]
Hi

Auf meiner lokalen DB verwende ich Apex 20.1 und habe erst die aktuelle Plugin Version genommen (macht im Source AIH##) und danach bin ich auf die (letzte Version ohne CKE5, macht im Source AIH#) Version 2.03. 

Wichtige Anmerkung, auf der Oracle Cloud kann ich innerhalb deiner Demo App (Super Sache, viel gelernt davon :) den Fehler reproduzieren. Also mit deinem Code! Siehe Anhang.

Gruß Mark

PS: Kein Stress, ich kann warten.

![Unleash](https://user-images.githubusercontent.com/36326420/112060631-b7fd9200-8b5d-11eb-9223-0e9b51a188ea.PNG)


Hier mal die zwei relevanten Code Blöcke von meiner DB:

Execute on Image Upload:

```
DECLARE
--    VR_FILE_NAME   VARCHAR2(200) := DBMS_RANDOM.STRING('l',8) || '_' || :FILE_NAME;
    VR_FILE_NAME   VARCHAR2(200) := :FILE_NAME;
    VR_MIME_TYPE   VARCHAR2(200) := :MIME_TYPE;
     /* Please ignore PLS-00382: expression is of wrong type
       because binding of :BLOB is not supported by current
       APEX PL/SQL Validator 
     */
    VR_BLOB        BLOB := :BLOB;
    /* You need to use V('P1_COL_NAME') because :P1_COL_NAME is not supported here */
    VR_COL_NAME    VARCHAR2(200) := 'COL_IMAGES';
BEGIN
    BEGIN
        APEX_COLLECTION.CREATE_COLLECTION(P_COLLECTION_NAME   => VR_COL_NAME);
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;

    APEX_COLLECTION.ADD_MEMBER(
        P_COLLECTION_NAME   => VR_COL_NAME,
        P_C001              => VR_FILE_NAME,
        P_C002              => VR_MIME_TYPE,
        P_BLOB001           => VR_BLOB
    );

    :P_OUT_PK   := VR_FILE_NAME;
EXCEPTION
    WHEN OTHERS THEN
        APEX_DEBUG.ERROR(SQLERRM);
        APEX_DEBUG.ERROR(DBMS_UTILITY.FORMAT_ERROR_STACK);
END;

```
Execute to get Image Sources

```
DECLARE
    VR_FILE_NAME     VARCHAR2(200);
    VR_MIME_TYPE     VARCHAR2(200);
     /* Please ignore PLS-00382: expression is of wrong type
       because binding of :BLOB is not supported by current
       APEX PL/SQL Validator 
     */
    VR_BINARY_FILE   BLOB;
    VR_PK            VARCHAR2(200) := :PK;
    /* You need to use V('P1_COL_NAME') because :P1_COL_NAME is not supported here */
    VR_COL_NAME      VARCHAR2(200) := 'COL_IMAGES';
BEGIN
    APEX_DEBUG.INFO('XXXXXXXXXXXXXX ' || VR_PK);

    SELECT
        C001,
        C002,
        BLOB001
    INTO
        VR_FILE_NAME,
        VR_MIME_TYPE,
        VR_BINARY_FILE
    FROM
        APEX_COLLECTIONS
    WHERE
        COLLECTION_NAME   = VR_COL_NAME
        AND C001              = VR_PK
        AND ROWNUM            = 1;

    :FILE_NAME     := VR_FILE_NAME;
    :MIME_TYPE     := VR_MIME_TYPE;
    :BINARY_FILE   := VR_BINARY_FILE;
EXCEPTION
    WHEN OTHERS THEN
        APEX_DEBUG.ERROR(SQLERRM);
        APEX_DEBUG.ERROR(DBMS_UTILITY.FORMAT_ERROR_STACK);
END;
```

**Comment by RonnyWeiss** [comment]
Also das sieht prinzipiell gut aus vom PL/SQL her. kannst du mal schauen, welche URL hinter den dem Bild quasi gesetzt ist? ÜBer klick auf Source solltest du das sehen können?

Hast du noch items to Submit gesetzt, welche eine SSP haben?`

Welche Patchset hast du installiert, nicht dass APEX mit dem neuen Feeature im 20.1 noch Bugs hatte. Weil ich teste ja online auf apex.world und dort ist ein APEX 20.2 installiert? 

Hast du dort ebenfalls einen Account? 

LG Ronny

**Comment by madmexx2002** [comment]
Hallo Ronny

Der Source ist in beiden Fällen absolut identisch mit Ausnahme der Zeichenfolge nach dem Plugin. Hatte ich gestern Abend schon mal getestet bevor ich auf die Ursache mit der URL gestoßen bin.

Ich übermittelt keine Items mit SSP.

Meine lokale Datenbank ist eine 18xe mit dem Apex 20.1 ohne Patchset - so wie sie jeder laden kann. In der Oracle Cloud ist Apex 20.2 installiert - ich nehme an in der aktuellsten Version mit Patchset. In der Cloud kann ich Dir gerne einen User einrichten. 

Sobald ich wieder am Rechner sitze werde ich mal auf Apex.Oracle.com einen WS hochziehen und testen. Ich melde mich dann nochmal mit mehr Informationen. 


Gruß Mark

**Comment by madmexx2002** [comment]
Hi Ronny

Auf apex.oracle.com (Application Express 20.2.0.00.20) habe ich gerade getestet. Mit der akutellsten Version von deinem Plugin läuft es hier mit beiden URL-Varianten ohne Probleme - allerdings auch CKE5.

In der Cloud ist es die Application Express 20.2.0.00.20 und lokal Application Express 20.1.0.00.13.
Das Source Attribut habe ich nochmals getestet. Unterschied nur im zweiten Teil nach %2F im Paramter p_request.
Auf der Cloud verwende ich Seite 26 (Unleash RichTextEditor 4) aus deiner Demo App.

Ist es beabsichtigt das im ALT-Attribut anders als in den vorhergenden Versionen anstatt aih# nun aih## steht. Habe in meinem Mailtemplates immer per Replace aus dem alt="aih# ein src="cid: gemacht. 

Gruß Mark

**Comment by RonnyWeiss** [comment]
Hallo 

Ja das musste sein und hängt mit dem CK5 zusammen. Ich vermute, dass es ein Bug ist. Kannst du dir mal den neusten Patch für APEX 20.1 installieren? Wir hatten da am Anfang auch recht Probleme mit den Friendly URLs, allerdings nicht mit dem CKE :-) 

Meine Demo App hat auch noch den CK4 dort tut es unter APEX 20.2

LG Ronny

**Comment by madmexx2002** [comment]
Hallo 

Ich habe leider keinen Zugang zum Service Bereich bei Oracle somit muss ich weiter ohne Patch auskommen. Auf meiner privaten Datenbank ist das kein Problem für mich. 

Auf der Cloud habe ich gerade geprüft, dort sind ein paar Patches installiert. Dort habe ich das gleiche Problem mit dem CKE4.

```
Number          Version
32006852	2020.10.22	Yes	2020-11-17 18:19:34
32006852	2020.11.17	Yes	2020-12-04 21:04:41
32006852	2020.12.03	Yes	2020-12-20 12:03:08
32006852	2021.01.13	Yes	2021-02-01 21:10:34
32006852	2021.02.05	Yes	2021-03-01 07:49:21
```

Nachdem ich erst in vier Wochen in der Arbeit auf 20.1 umsteige, würde ich jetzt keine weitere Zeit in die Ursachenforschung investieren und abwarten ob in dieser sicherlich gepatchen Version der Fehler noch auftritt. Unter umständen wird uns die Option "Friendly URL" gar nicht erst gestattet. Bisher sind wir mit der alten URL auch klar gekommen. 
Ich werde mich mit dann mit neuen Erkenntnissen nochmals bei Dir melden.

Vielen Dank für deine Unterstüzung.

Gruß Mark

**Comment by RonnyWeiss** [comment]
Hallo

Vielen Dank für die ausführliche Antwort. Eine Idee wäre noch dir den Patch über eure Admins zu besorgen, welche eben Zugang zum Oracle Support haben. 

Da es eben ein Problem in der API von APEX ist https://docs.oracle.com/en/database/oracle/application-express/20.2/aexjs/apex.server.html#.pluginUrl , kann ich eben leider nicht weiter helfen. Ggf. kannst du ja Privat nochmal APEX 20.2 testen :-)

Ich würde den Issue erstmal schließen und Sie melden sich nochmal, falls es weiterhin ein Problem ist

LG Ronny

**Comment by madmexx2002** [comment]
Hi

Naja bei Apex 20.2 kann ich dann auch den CKE5 verwenden - dort funktioniert dein Plugin mit beiden URL's ohne Probleme. Ich muss mich bei der wahl der Apex-Version nach der Arbeit richten. Die Oracle Datenbanken werden von einem externen Dienstleister betrieben - somit habe ich schlechte Karten für den Patch.

Ich werde mich bei Dir melden und berichten ob das Problem noch besteht. Bis dahin darfst das Ticket gerne schließen.

LG Mark

**Comment by RonnyWeiss** [comment]
Supi

Wie gesagt mit der CKE Version hat es nichts zu tun bei mir im apex.oracle.com hat es auch in CKE4 funktioniert:

https://apex.oracle.com/pls/apex/f?p=103428:26 also ich friendly urls anhabe es war gefühlt ein Bug eben in der JS API die ich oben verlinkt habe.

LG Ronny

**Comment by madmexx2002** [comment]
Ich wollte damit nicht sagen dein Plugin ist der Fehler. Nur eben das ich bei 20.2 einfach mit dem CKE5 arbeiten kann.
Ich habe mal durch die Patchnotes geschaut, dort gibt es Einträge zum Thema "Friendly URL". Anzunehmen das deine Vermutung zutreffend ist. Wir werden sehen...

Vielen Dank & LG Mark
