### ISSUE TITLE
Dynamic selection on mobile

### ISSUE THREAD

**Issue by mikedavidson1959blue** [RonnyWeiss/APEX-Unleash-RichTextEditor#15]
Hi Ronnie, I was wondering if you could possibly help me. I am now also using your brilliant dynamic selection plug-in on a reflow report. On my desktop it work great, however on both my ipad and my iphone I just cannot get it to work. Instead on seeing checkboxes for the selectable items I just get the text wrapped in '{{ }}'. I have tried to attach to this ticket a screen capture from my ipad which hopefully you will be able to see. I looked at all the obvious things but cant see what's wrong. The plugin is definitely firing on my desktop, ipad and phone as I inserted a simple alert into your javascript which pops up as expected.

Really appreciate hearing back and if resolved it definitely worth a lot more coffees to you!

Yours,

Mike Davidson
www.cConix.com

![dynamic selection](https://user-images.githubusercontent.com/66328510/126848140-7b0a1e3f-a1b3-4ada-bbc5-789f6603f0ad.png)

**Comment by RonnyWeiss** [comment]
Hello Thank you for your request. Could you also get this error when using not chrome and not safari?

**Comment by RonnyWeiss** [comment]
I tried it on my iPad in Safari and Chrome and both works. Could you please check console for any js errors?

**Comment by RonnyWeiss** [comment]
Because the top left image are also not loading so maybe you have so trouble with static files or so

**Comment by mikedavidson1959blue** [comment]
Hi Ronny,

It is a really strange one. Both my app and your sample app work perfectly on my laptop. Your sample app also works perfectly on my iPad and iPhone, my app does not render correctly on both my iPad and iPhone. I did insert an alert into the js file and the plugin is definitely firing on the mobile devices. I think I'll need to add some more debug just to see how or where it's breaking. As an aside, can you tell me how to access the console on the mobile device to check for js errors? I've done some goggling but could not find anything useful.

Yours,


[horizontal bar]
Mike Davidson
cConix, CEO
[cConix]

Landline - (1) 403-538-3196
Mobile - (1) 403-629-4009
email - ***@***.***Conix.com

Suite 300, 840 6th Avenue SW
Calgary, Alberta T2P 3E5

http://www.cConix.com<http://www.cconix.com/>


________________________________

**Comment by RonnyWeiss** [comment]
The Problem is that something crashes on Safari engine in your App. Which other Plugins are you using on the page? Maybe you could deactivate All other ja to check wheres the Problem. On ipdad you dont have console. So you can only check it Out be deactivating other js on the page

**Comment by RonnyWeiss** [comment]
So when my sample app Works it can Not be a Problem with the plugin itself.

**Comment by mikedavidson1959blue** [comment]
Hi Ronnie,

The issue was actually an Apex page issue. I deleted the page and rebuilt it, and now everything works well. Sorry for the inconvenience.

Mike

[horizontal bar]
Mike Davidson
cConix, CEO
[cConix]

Landline - (1) 403-538-3196
Mobile - (1) 403-629-4009
email - ***@***.***

Suite 300, 840 6th Avenue SW
Calgary, Alberta T2P 3E5

http://www.cConix.com<http://www.cconix.com/>


________________________________

**Comment by RonnyWeiss** [comment]
Perfectly! So have fun with the plug-in and a nice week!
