### ISSUE TITLE
Usage of the plugin with real tables

### ISSUE THREAD

**Issue by tomdk** [RonnyWeiss/APEX-Unleash-RichTextEditor#3]
Hi!

I'm trying to implement the plugin into my project and so far it's looking good. However I'm running into one problem. Before going into detail i'll explain what I'm doing.

I have a table CONTACTS which has a CLOB field (the one we will be editing with the RTE) and all the images should go into a table called CONTACT_ATTACHMENTS which more or less has the same columns as you're using in the collection. In short, I'm replacing the collection to a TABLE.

At the moment everything is going just fine, until I try to display the images. Both in the RTE as in the REPORT I'm using for debugging, the images are not shown. I'm focussing at the report for now, the issues I see is the following:

The query of the report:

SELECT
CONTACT_ATTACHMENT_ID,
CONTACT_ID
    SEQ_ID,
    FILE_NAME,
    MIME_TYPE,
    ROUND(DBMS_LOB.GETLENGTH(CONTENT)/1024) AS BLOB_SIZE,
    APEX_PAGE.GET_URL(
        P_REQUEST   => 'APPLICATION_PROCESS=DI',
        P_ITEMS     => 'P1001_FILE_NAME',
        P_VALUES    =>  FILE_NAME
    ) AS IMG_URL
FROM
    CONTACT_ATTACHMENTS
WHERE
    CONTACT_ID   = :P1001_CONTACT_ID

The problem is in the URL, could you tell me where APPLICATION_PROCESS=DI is defined? I couldn't find it in the DEMO application either. Maybe I'm just looking past something but I think this is the cause of the issue.

Help is greatly appreciated!

**Comment by RonnyWeiss** [comment]
did you activate the upload of images and add there so plsql maybe a api where blob should be created?

**Comment by RonnyWeiss** [comment]
Closed because no reaction
