### ISSUE TITLE
switching between 'Save...' and 'Load...' in APEX builder resets the PL/SQL code to defaults

### ISSUE THREAD

**Issue by dgrootem** [RonnyWeiss/APEX-Unleash-RichTextEditor#4]
when switching the function type between 'load richtexteditor content' and 'save richtexteditor content' the code in the different text areas ('SQL Source', 'Execute on image upload', ...) is being reset to default values...

APEX version = 19.1

**Comment by RonnyWeiss** [comment]
Yes but that's an APEX feature/bug. Please create a bug for APEX Dev team or when you use app builder just click on undo. Hope this helps
