### ISSUE TITLE
Mike Davidson

### ISSUE THREAD

**Issue by miked1959blue** [RonnyWeiss/APEX-Unleash-RichTextEditor#5]
Hi Ronny,

I downloaded the plugin and tried to install it in my Apex 19,1 environment. 

I went to Shared Components->Plug-Ins->Import, selected the downloaded apexplugin.json file, file  type was set to 'Plug-In', pressed Next, got message 'The export file has been imported successfully.', pressed Next again, and got 'File is not a valid Application Express plug-in export file. ' - can you please tell me what I did wrong? 

Your plug-in looks brilliant and it exactly what I am looking for,

Yours,

Mike Davidson

**Comment by RonnyWeiss** [comment]
please read documentation how to import plugin in apex. At first you need to use the sql file not the json file. The json file is jsut for apex.world as info file.

**Comment by miked1959blue** [comment]
Hi Ronny, thanks for the email but I still seem to be struggling. 

I installed the plugin using the SQL file and all appeared to work. 

The resultant plugin appears as a Dynamic Action rather than an Item - is this correct? 

I have read through all the Oracle documentation on importing plug-ins and I think I've followed the steps properly - the others I've imported all work well.

Hoping that you can provide some guidance.

Yours,

Mike Davidson

**Comment by miked1959blue** [comment]
Hi Ronny,

Further to my last email, I notice that Dynamic Action is correct. I am using Apex 19.1, when I try to drag an image into the RTE space I get a JavaScript error saying that the object does not support the 'contains' property - is there something I need to configure on the CKEditor? Do I also need to create collection to store the images or is there a default collection configured with the plugin?

I tried to download your app to check-out the config but it would not load into my Apex environment, I assume that's because you are on a later version of Apex, would it be possible to get a 19.1 copy of the sample app?

As always, really looking forward to hearing back.

Yours,

Mike Davidson
