### ISSUE TITLE
RTE Plugin

### ISSUE THREAD

**Issue by miked1959blue** [RonnyWeiss/APEX-Unleash-RichTextEditor#6]
Hi Ronny, thanks for the last email but I still seem to be struggling.

I installed the plugin using the SQL file and all appeared to work.

The resultant plugin appears as a Dynamic Action rather than an Item - is this correct?

I have read through all the Oracle documentation on importing plug-ins and I think I've followed the steps properly - the others I've imported all work well.

Hoping that you can provide some guidance.

Yours,

Mike Davidson

**Comment by miked1959blue** [comment]
Hi Ronny,

Further to my last email, I notice that Dynamic Action is correct. I am using Apex 19.1, when I try to drag an image into the RTE space I get a JavaScript error saying that the object does not support the 'contains' property - is there something I need to configure on the CKEditor? Do I also need to create collection to store the images or is there a default collection configured with the plugin?

Also I tried to download your app to check-out the config but it would not load into my Apex environment, I assume that's because you are on a later version of Apex, would it be possible to get a 19.1 copy of the sample app?

As always, really looking forward to hearing back.

Yours,
Mike Davidson

**Comment by RonnyWeiss** [comment]
can you please tell me what you have done? do you use a richtexteditor item and set these as affected item in the plugin?

**Comment by miked1959blue** [comment]
Hi Ronny, 

I really appreciate the email. 

All I have done so far is install the Plug-In. 

In my app I have several Rich Text Fields, all associated with table columns of type clob.

![image](https://user-images.githubusercontent.com/52088975/79261541-3f6e5b80-7e4d-11ea-904b-77934c91ed8d.png)

The apex page (version 19.1) is quite simple:

![image](https://user-images.githubusercontent.com/52088975/79261833-a0962f00-7e4d-11ea-8425-cba9ea6b505b.png)

The Rich Text Editor I am using is the one supplied with Apex i.e. CKEditor. 

![image](https://user-images.githubusercontent.com/52088975/79260884-37fa8280-7e4c-11ea-96c6-2b9bafe3afcc.png)

When I try dragging an image into the RTE I get the JavaScript error, hopefully you can see the attachment below:

![image](https://user-images.githubusercontent.com/52088975/79261135-9fb0cd80-7e4c-11ea-82f7-f54534a468db.png)

![image](https://user-images.githubusercontent.com/52088975/79261271-d0910280-7e4c-11ea-8c38-496a655ae217.png)

![image](https://user-images.githubusercontent.com/52088975/79261340-ed2d3a80-7e4c-11ea-96de-8828c2b7ea0c.png)
