### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by miked1959blue** [RonnyWeiss/APEX-Unleash-RichTextEditor#7]
Hi Ronny,

I finally managed to upload your app via the Oracle Apex 20 environment, saw the sample setup and successfully managed to get it all working in my environment - it’s super cool. 

I have however a question. 

Obviously the sample uses collections which only hold session specific data. 

All my images are stored in a table so at the start of each session I re-populate the collection (IMAGE-COLLECTION) with all the valid image blobs and details. 

However, when I login again to my app and then view my rich text field on the page it just shows the alt src text where the images used to be. I assume that the embedded links in the rich text clob must be preserving either the old session ID or some other legacy session variable. 

Do you know how I can overcome this such that the rich text content is preserved, showing the embedded images, across sessions; possibly replacing some of the ‘img’ text or refreshing the ‘img’ links? As an aside, I’ve verified that the collection content is exactly the same after I re-login. 

Really appreciate any feedback.

Mike

**Comment by RonnyWeiss** [comment]
Why do you no change my sample Code with your table? The plug-ins just execute SQL and PL/SQL you do not need APEX_COLLECTION. When you need further help please create new issue. Have a nice day thank you.
